import {
  AlertTriangle,
  Brain,
  Briefcase,
  FolderKanban,
  Plus,
  Search,
  Settings,
  Shield,
  Users,
  Zap,
} from "lucide-react";
import Link from "next/link";
function SidebarItem({
  label,
  active = false,
}: {
  label: string;
  active?: boolean;
}) {
  return (
    <button
      className={`rounded-full px-4 py-2 text-sm font-medium transition ${
        active
          ? "bg-[#8ea8ff] text-[#0b1020]"
          : "text-white/65 hover:bg-white/[0.05] hover:text-white"
      }`}
    >
      {label}
    </button>
  );
}

function MiniDecisionCard({
  title,
  icon: Icon,
  score,
  sublabel,
  color,
}: {
  title: string;
  icon: React.ElementType;
  score: string;
  sublabel: string;
  color: string;
}) {
  return (
    <div className="rounded-[24px] border border-white/8 bg-white/[0.03] p-4 shadow-xl shadow-black/20">
      <div className="mb-5 flex items-start justify-between">
        <div
          className="flex h-10 w-10 items-center justify-center rounded-2xl"
          style={{
            backgroundColor: `${color}15`,
            color,
          }}
        >
          <Icon size={18} />
        </div>

        <div className="text-right">
          <p className="text-lg font-semibold text-white">{score}</p>
          <p className="text-[10px] uppercase tracking-[0.18em] text-white/35">
            {sublabel}
          </p>
        </div>
      </div>

      <h3 className="text-sm font-semibold text-white">{title}</h3>
    </div>
  );
}

export default function DecisionCenterPage() {
  return (
    <main className="min-h-screen bg-[#05060b] text-white">
      <div className="mx-auto max-w-[1450px] px-4 py-5 sm:px-6 lg:px-8">
        <header className="mb-8 flex items-center justify-between rounded-[28px] border border-white/8 bg-[#070910]/90 px-5 py-4 shadow-2xl shadow-black/30 backdrop-blur">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-[#8ea8ff] to-[#6d84ff] text-[#0b1020]">
              <Brain size={20} />
            </div>
            <div>
              <p className="text-sm font-semibold text-white">Pilot</p>
              <p className="text-xs text-white/40">Decision Intelligence</p>
            </div>
          </div>
<nav className="hidden items-center gap-2 md:flex">
  <Link href="/dashboard">
    <SidebarItem label="Projects" />
  </Link>

  <Link href="/ai-insights">
    <SidebarItem label="AI Insights" />
  </Link>

  <Link href="/decision-center">
    <SidebarItem label="Decision Center" active />
  </Link>

  <Link href="/resource-hub">
    <SidebarItem label="Resources" />
  </Link>

  <Link href="/settings">
    <SidebarItem label="Settings" />
  </Link>
</nav>
          <div className="flex items-center gap-3">
            <div className="hidden items-center gap-2 rounded-2xl border border-white/8 bg-white/[0.03] px-4 py-2 text-sm text-white/45 sm:flex">
              <Search size={16} />
              <span>Search decisions</span>
            </div>

            <div className="h-9 w-9 rounded-full bg-gradient-to-br from-[#8ea8ff] to-[#6d84ff]" />
          </div>
        </header>

        <section className="mb-8">
          <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-[#8ea8ff]/15 bg-[#8ea8ff]/10 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#9eb7ff]">
            <Zap size={12} />
            Live Neural Processing
          </div>

          <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
            <div>
              <h1 className="text-4xl font-semibold tracking-tight text-white sm:text-5xl">
                Decision Center
              </h1>
              <p className="mt-4 max-w-2xl text-base leading-7 text-white/50">
                Autonomous strategic recommendations generated by Pilot’s core
                intelligence. Review and authorize operational shifts based on
                real-time workload, risk, and project signals.
              </p>
            </div>

            <div className="rounded-[24px] border border-white/8 bg-white/[0.03] px-6 py-4 text-right shadow-xl shadow-black/20">
              <p className="text-3xl font-semibold text-[#9eb7ff]">14</p>
              <p className="text-[10px] uppercase tracking-[0.2em] text-white/35">
                Pending Decisions
              </p>
            </div>
          </div>
        </section>

        <section className="grid gap-6 xl:grid-cols-[1.65fr_0.85fr]">
          <div className="rounded-[32px] border border-white/8 bg-[radial-gradient(circle_at_top_left,rgba(142,168,255,0.16),transparent_36%),linear-gradient(135deg,rgba(255,255,255,0.06),rgba(255,255,255,0.03))] p-6 shadow-2xl shadow-black/30">
            <div className="mb-6 flex items-start justify-between gap-4">
              <div>
                <p className="text-[10px] uppercase tracking-[0.2em] text-white/35">
                  High Impact Action
                </p>
                <h2 className="mt-3 text-3xl font-semibold tracking-tight text-white">
                  Resource Reallocation
                </h2>
              </div>

              <div className="rounded-2xl border border-[#8ea8ff]/20 bg-[#8ea8ff]/10 px-4 py-3 text-right">
                <div className="flex items-center justify-end gap-2">
                  <Zap size={14} className="text-[#9eb7ff]" />
                  <span className="text-lg font-semibold text-[#9eb7ff]">94%</span>
                </div>
                <p className="mt-1 text-[10px] uppercase tracking-[0.18em] text-white/35">
                  Confidence
                </p>
              </div>
            </div>

            <div className="grid gap-5 lg:grid-cols-[1.2fr_0.9fr]">
              <div className="rounded-[24px] border border-white/6 bg-white/[0.03] p-5">
                <p className="mb-3 text-[10px] uppercase tracking-[0.18em] text-white/35">
                  Reasoning
                </p>
                <p className="text-sm leading-7 text-white/70">
                  Market volatility in the APAC sector has increased by
                  <span className="font-semibold text-[#9eb7ff]"> 14.2%</span>.
                  Redirecting
                  <span className="font-semibold text-[#9eb7ff]"> 30%</span> of
                  underutilized GPU clusters from internal testing to the Real-Time
                  Trading workload is likely to raise output efficiency inside
                  current delivery windows.
                </p>
              </div>

              <div className="rounded-[24px] border border-white/6 bg-white/[0.03] p-5">
                <p className="mb-4 text-[10px] uppercase tracking-[0.18em] text-white/35">
                  Projected Impact
                </p>

                <div className="space-y-5">
                  <div>
                    <div className="mb-2 flex items-center justify-between text-sm">
                      <span className="text-white/65">Revenue Gain</span>
                      <span className="font-semibold text-[#9eb7ff]">+$2.1M</span>
                    </div>
                    <div className="h-2 rounded-full bg-white/[0.06]">
                      <div className="h-2 w-[82%] rounded-full bg-gradient-to-r from-[#7e9eff] to-[#9eb7ff]" />
                    </div>
                  </div>

                  <div>
                    <div className="mb-2 flex items-center justify-between text-sm">
                      <span className="text-white/65">Efficiency</span>
                      <span className="font-semibold text-[#ff8fb1]">+18.5%</span>
                    </div>
                    <div className="h-2 rounded-full bg-white/[0.06]">
                      <div className="h-2 w-[68%] rounded-full bg-gradient-to-r from-[#ff73a5] to-[#ff9bbd]" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
<div className="mt-6 flex flex-wrap gap-3">
  <button className="rounded-2xl bg-[#8ea8ff] px-6 py-3 text-sm font-semibold text-[#0b1020] transition hover:brightness-110">
    Approve Reallocation
  </button>

  <button className="rounded-2xl border border-white/10 bg-white/[0.03] px-6 py-3 text-sm font-medium text-white/75 transition hover:bg-white/[0.05] hover:text-white">
    Reject
  </button>

  <Link
    href="/resource-hub"
    className="rounded-2xl border border-white/10 bg-white/[0.03] px-6 py-3 text-sm font-medium text-white/75 transition hover:bg-white/[0.05] hover:text-white"
  >
    Open Resource Hub
  </Link>

  <Link
    href="/ai-insights"
    className="rounded-2xl border border-white/10 bg-white/[0.03] px-6 py-3 text-sm font-medium text-white/75 transition hover:bg-white/[0.05] hover:text-white"
  >
    Back to AI Insights
  </Link>
</div>
          </div>

          <div className="rounded-[32px] border border-white/8 bg-white/[0.03] p-6 shadow-2xl shadow-black/25">
            <div className="mb-5 flex items-center justify-between">
              <span className="rounded-full border border-[#ff8bd8]/20 bg-[#ff8bd8]/10 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#ff9ce0]">
                Network Update
              </span>
            </div>

            <h3 className="text-2xl font-semibold text-white">Protocol Upgrade</h3>

            <p className="mt-4 text-sm leading-7 text-white/60">
              Deploying L3-optimized patches will reduce cross-chain settlement time
              by <span className="font-semibold text-[#9eb7ff]">40%</span>.
              Confidence remains high despite minor network congestion risk.
            </p>

            <div className="mt-6">
              <div className="mb-2 flex items-center justify-between">
                <span className="text-4xl font-semibold text-white">88%</span>
                <span className="text-sm text-white/45">Success likelihood</span>
              </div>

              <div className="h-2 w-full rounded-full bg-white/[0.06]">
                <div className="h-2 w-[88%] rounded-full bg-gradient-to-r from-[#ff8bd8] to-[#9eb7ff]" />
              </div>
            </div>

            <div className="mt-8 flex flex-wrap gap-3">
              <button className="rounded-2xl bg-white px-5 py-3 text-sm font-semibold text-[#0b1020] transition hover:opacity-90">
                Authorize Protocol
              </button>
              <button className="rounded-2xl border border-white/10 px-5 py-3 text-sm font-medium text-white/70 transition hover:bg-white/[0.04] hover:text-white">
                Dismiss
              </button>
            </div>
          </div>
        </section>

        <section className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-4">
          <MiniDecisionCard
            title="Vendor Terminate"
            icon={AlertTriangle}
            score="72%"
            sublabel="Risk Mitigation"
            color="#ff6b6b"
          />
          <MiniDecisionCard
            title="Inventory Shift"
            icon={Briefcase}
            score="91%"
            sublabel="Efficiency Gain"
            color="#8ea8ff"
          />
          <MiniDecisionCard
            title="Auto-Pay Update"
            icon={Shield}
            score="87%"
            sublabel="Confidence"
            color="#7f9dff"
          />
          <div className="flex items-center justify-center rounded-[24px] border border-dashed border-white/10 bg-white/[0.02] p-4 transition hover:bg-white/[0.04]">
            <button className="flex h-12 w-12 items-center justify-center rounded-full bg-[#8ea8ff] text-[#0b1020] shadow-lg shadow-[#8ea8ff]/20 transition hover:scale-105">
              <Plus size={20} />
            </button>
          </div>
        </section>

        <nav className="mt-8 flex justify-center md:hidden">
          <div className="flex items-center gap-2 rounded-full border border-white/8 bg-[#070910]/95 px-3 py-2">
            <SidebarItem label="Projects" />
            <SidebarItem label="Tasks" active />
            <SidebarItem label="Activity" />
            <SidebarItem label="Settings" />
          </div>
        </nav>
      </div>
    </main>
  );
}